# -*- coding: utf-8 -*-
"""Utils.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CQa_XQ4M0BLPEmc-VlGJKoLNcjPxrhEO

Setting up solaris
"""

!add-apt-repository ppa:ubuntugis/ppa -y
!apt-get update
!apt-get install python-numpy gdal-bin libgdal-dev python3-rtree

!pip install solaris==0.2.0

"""Install other necessary packages"""

!pip install rasterio
!pip install geopandas
!pip install descartes
!pip install rio-tiler
!pip3 install py7zr

"""Importing necessary packages"""

import torch
import rasterio
import py7zr
import os
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from pycocotools.coco import COCO
from torch import nn
from torchvision import datasets, transforms, models

"""Download Multispectral dataset from dropbox and extract folder"""

def DownloadMultiSpectralDataset():
  !wget https://www.dropbox.com/s/nj1iddz4dhvdwa1/Multispectral.7z?dl=0
  os.rename('Multispectral.7z?dl=0', 'Multispectral.7z')
  ExtractImages('Multispectral.7z', './')

"""Download Pansharpened dataset from Dropbox and extract folder"""

def DownloadPanSharpenedDataset():
  !wget https://www.dropbox.com/s/qb0dfxjafuodc27/Pansharpened.7z?dl=0
  os.rename('Pansharpened.7z?dl=0', 'Pansharpened.7z')
  ExtractImages('Pansharpened.7z', './')

"""Extract 7z folders"""

def ExtractImages(in_path, out_path):
  with py7zr.SevenZipFile(in_path, mode='r') as z:
    z.extractall(out_path)

DownloadPanSharpenedDataset()

in_path = './Pansharpened/HR_TIF_Files.7z'     #path of zip files
out_path = './LandfillDataset'                                   #output path of extracted files
ExtractImages(in_path, out_path)